# Generated by Django 4.0 on 2022-01-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('shipping_addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippinAddress',
            new_name='ShippingAddress',
        ),
    ]
