# Generated by Django 4.0 on 2022-01-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_pomo_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pomo_code',
            new_name='promo_code',
        ),
    ]
