# Generated by Django 4.0 on 2022-01-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
