# Generated by Django 4.0 on 2022-01-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_stock_product_type_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_color',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
