# Generated by Django 4.0 on 2022-01-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_type_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
